"""Digest Notification Provider

Delivers the daily performance digest via configured channels.
Channels are opt-in via env vars — configure none, one, or both.

Email:  SMTP_HOST, SMTP_PORT (default 587), SMTP_USER, SMTP_PASSWORD,
        DIGEST_EMAIL_FROM, DIGEST_EMAIL_TO (comma-separated)
GChat:  GCHAT_WEBHOOK_URL

Call deliver_digest(digest_dict) from the APScheduler job.
"""
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

logger = logging.getLogger(__name__)


def _email_configured() -> bool:
    """Return True when SMTP credentials and a recipient list are present."""
    return bool(
        os.environ.get("SMTP_HOST")
        and os.environ.get("SMTP_USER")
        and os.environ.get("DIGEST_EMAIL_TO")
    )


def _gchat_configured() -> bool:
    """Return True when a GChat webhook URL is present."""
    return bool(os.environ.get("GCHAT_WEBHOOK_URL"))


def format_email_html(digest: dict) -> str:
    """Render digest as HTML email.

    Doane brand: #FF7900 orange, #1F3864 navy.
    Includes: date header, workflow table (name/total/failed/avg_ms/trend),
    regressions section, recommendations stub, worker health summary,
    and footer with link to Conductor Companion.
    """
    date_str = digest.get("date", "Unknown")
    workflows = digest.get("workflows", [])
    regressions = digest.get("regressions", [])
    worker_health = digest.get("worker_health", {})

    # Build workflow rows
    rows_html = ""
    for wf in workflows:
        trend_symbol = {"up": "&#x2191;", "down": "&#x2193;", "stable": "&#x2192;", "new": "&#x2605;"}.get(
            wf.get("trend", "stable"), ""
        )
        failed_color = "#FF7900" if wf.get("failed", 0) > 0 else "inherit"
        rows_html += (
            f"<tr>"
            f"<td style='padding:4px 8px;border-bottom:1px solid #ddd'>{wf.get('name', '')}</td>"
            f"<td style='padding:4px 8px;border-bottom:1px solid #ddd;text-align:right'>{wf.get('total', 0)}</td>"
            f"<td style='padding:4px 8px;border-bottom:1px solid #ddd;text-align:right;color:{failed_color}'>{wf.get('failed', 0)}</td>"
            f"<td style='padding:4px 8px;border-bottom:1px solid #ddd;text-align:right'>{wf.get('avg_ms', 0):,}ms</td>"
            f"<td style='padding:4px 8px;border-bottom:1px solid #ddd;text-align:center'>{trend_symbol}</td>"
            f"</tr>"
        )

    # Build regressions section
    reg_html = ""
    if regressions:
        reg_html = "<h3 style='color:#FF7900'>&#x26A0; Performance Regressions</h3><ul>"
        for reg in regressions:
            reg_html += (
                f"<li><strong>{reg.get('workflow_name')}</strong> is "
                f"{reg.get('pct_slower', 0):.1f}% slower than 7-day avg "
                f"({reg.get('current_avg_ms', 0):,}ms vs {reg.get('historical_avg_ms', 0):,}ms avg)</li>"
            )
        reg_html += "</ul>"

    # Build worker health summary
    health_html = "<ul>"
    for task_type, status in worker_health.items():
        color = "#FF7900" if status in ("down", "no_workers", "slow_poll") else "green"
        health_html += f"<li style='color:{color}'><strong>{task_type}</strong>: {status}</li>"
    health_html += "</ul>"

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset='utf-8'></head>
<body style='font-family:Arial,sans-serif;max-width:800px;margin:0 auto;color:#222'>
  <div style='background:#1F3864;color:#fff;padding:16px 24px;border-radius:4px 4px 0 0'>
    <h1 style='margin:0;font-size:20px'>Conductor Companion — Daily Digest</h1>
    <p style='margin:4px 0 0;font-size:14px;color:#ccc'>{date_str}</p>
  </div>
  <div style='padding:16px 24px;border:1px solid #ddd;border-top:none'>
    <h2 style='color:#1F3864'>Workflow Summary</h2>
    <table style='width:100%;border-collapse:collapse;font-size:14px'>
      <thead>
        <tr style='background:#1F3864;color:#fff'>
          <th style='padding:8px;text-align:left'>Workflow</th>
          <th style='padding:8px;text-align:right'>Total</th>
          <th style='padding:8px;text-align:right'>Failed</th>
          <th style='padding:8px;text-align:right'>Avg Duration</th>
          <th style='padding:8px;text-align:center'>Trend</th>
        </tr>
      </thead>
      <tbody>{rows_html}</tbody>
    </table>
    {reg_html}
    <h2 style='color:#1F3864'>Worker Health</h2>
    {health_html}
    <hr style='border:none;border-top:1px solid #eee;margin:24px 0'>
    <p style='font-size:12px;color:#888'>
      Generated by
      <a href='http://localhost:5000' style='color:#FF7900'>Conductor Companion</a>.
    </p>
  </div>
</body>
</html>"""
    return html


def format_gchat_message(digest: dict) -> str:
    """Render digest as GChat card text (Markdown-ish).

    Skimmable: emoji status indicators, top 5 workflows by volume,
    regressions highlighted, recommendation count.
    # TODO(gchat): confirm whether to use simple text or Cards v2 JSON
    """
    date_str = digest.get("date", "Unknown")
    workflows = digest.get("workflows", [])
    regressions = digest.get("regressions", [])
    worker_health = digest.get("worker_health", {})

    # Top 5 workflows by total volume
    top5 = sorted(workflows, key=lambda w: w.get("total", 0), reverse=True)[:5]

    lines = [
        f"*Conductor Companion — Daily Digest* ({date_str})",
        "",
        "*Top Workflows by Volume:*",
    ]
    for wf in top5:
        trend_sym = {"up": "↑", "down": "↓", "stable": "→", "new": "★"}.get(
            wf.get("trend", "stable"), ""
        )
        failed = wf.get("failed", 0)
        status_sym = "🔴" if failed > 0 else "🟢"
        lines.append(
            f"  {status_sym} `{wf.get('name')}` — {wf.get('total', 0)} runs, "
            f"{failed} failed, {wf.get('avg_ms', 0):,}ms avg {trend_sym}"
        )

    if regressions:
        lines += ["", f"⚠️ *{len(regressions)} Regression(s) Detected:*"]
        for reg in regressions[:3]:
            lines.append(
                f"  - `{reg.get('workflow_name')}` {reg.get('pct_slower', 0):.1f}% slower than avg"
            )

    # Worker health summary
    problem_workers = [t for t, s in worker_health.items() if s in ("down", "no_workers", "slow_poll")]
    if problem_workers:
        lines += ["", f"🔧 *Worker Issues ({len(problem_workers)}):* " + ", ".join(f"`{w}`" for w in problem_workers[:5])]

    lines += [
        "",
        "_View full digest: http://localhost:5000_",
    ]
    return "\n".join(lines)


def send_email(subject: str, html_body: str) -> dict:
    """Send an HTML email via SMTP.

    Uses STARTTLS. SMTP_PORT defaults to 587.
    Returns {sent: bool, error: str|None}.
    """
    if not _email_configured():
        return {"sent": False, "error": "email not configured"}

    smtp_host = os.environ["SMTP_HOST"]
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = os.environ["SMTP_USER"]
    smtp_password = os.environ.get("SMTP_PASSWORD", "")
    from_addr = os.environ.get("DIGEST_EMAIL_FROM", smtp_user)
    to_addrs = [a.strip() for a in os.environ["DIGEST_EMAIL_TO"].split(",") if a.strip()]

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = from_addr
        msg["To"] = ", ".join(to_addrs)
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        with smtplib.SMTP(smtp_host, smtp_port, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(from_addr, to_addrs, msg.as_string())

        logger.info("digest email sent to %d recipient(s)", len(to_addrs))
        return {"sent": True, "error": None}
    except Exception as exc:
        logger.error("digest email send failed: %s", exc)
        return {"sent": False, "error": str(exc)[:200]}


def send_gchat(message: str) -> dict:
    """POST a message to the configured GChat webhook.

    Returns {sent: bool, error: str|None}.
    """
    if not _gchat_configured():
        return {"sent": False, "error": "gchat not configured"}

    webhook_url = os.environ["GCHAT_WEBHOOK_URL"]
    try:
        resp = requests.post(
            webhook_url,
            json={"text": message},
            timeout=10,
        )
        resp.raise_for_status()
        logger.info("digest gchat message sent")
        return {"sent": True, "error": None}
    except Exception as exc:
        logger.error("digest gchat send failed: %s", exc)
        return {"sent": False, "error": str(exc)[:200]}


def deliver_digest(digest: dict) -> dict:
    """Deliver the digest to all configured channels.

    Called by the APScheduler job after generating the daily digest.
    Failures are logged but never raised — digest delivery must not
    crash the scheduler.

    Returns {channels_attempted, channels_succeeded, errors}.
    """
    channels_attempted = 0
    channels_succeeded = 0
    errors = []

    date_str = digest.get("date", "Unknown")
    subject = f"Conductor Companion — Daily Digest {date_str}"

    # Email channel
    if _email_configured():
        channels_attempted += 1
        try:
            html_body = format_email_html(digest)
            result = send_email(subject, html_body)
            if result.get("sent"):
                channels_succeeded += 1
            else:
                errors.append({"channel": "email", "error": result.get("error")})
        except Exception as exc:
            logger.error("deliver_digest email error: %s", exc)
            errors.append({"channel": "email", "error": str(exc)[:200]})

    # GChat channel
    if _gchat_configured():
        channels_attempted += 1
        try:
            message = format_gchat_message(digest)
            result = send_gchat(message)
            if result.get("sent"):
                channels_succeeded += 1
            else:
                errors.append({"channel": "gchat", "error": result.get("error")})
        except Exception as exc:
            logger.error("deliver_digest gchat error: %s", exc)
            errors.append({"channel": "gchat", "error": str(exc)[:200]})

    return {
        "channels_attempted": channels_attempted,
        "channels_succeeded": channels_succeeded,
        "errors": errors,
    }
